assess_request:
  description: >
    Determine what the caller needs and provide a helpful response.
    If they need general information about the practice, services, or have 
    general questions, provide that information directly.
    If they want to book an appointment, acknowledge this and indicate it.
  expected_output: >
    A clear response to the caller that addresses their needs.
  agent: receptionist
  
handle_appointment:
  description: >
    The caller wants to book a doctor's appointment. Collect all required information:
    full name, date of birth, preferred date and time, reason for visit, insurance 
    information, and contact number. After collecting all information, 
    provide a confirmation summary and any preparation instructions.
  expected_output: >
    Complete appointment details and confirmation information.
  agent: appointment_specialist